openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'KDD Project'
  description: 'KDshim Diary'
servers:
  - url: http://localhost:8080

paths:
  /swaggerTest:
    get:
      summary: simple swagger test api
      description: simple swagger test api
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: string
                example: responseTest
        400:
          description: fail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

  /myLinks:
    get:
      summary: 저장된 모든 링크 가져오기
      description: 모든 링크를 긁어온다
      responses:
        200:
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyLinkDto'
        400:
          description: 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'


components:
  schemas:
    MyLinkDto:
      type: object
      properties:
        name:
          type: string
          description: 해당 url 이름
          example: Java Stream API는 왜 for-loop보다 느릴까?
        url:
          type: string
          description: 링크(raw url)
          example: https://jypthemiracle.medium.com/java-stream-api는-왜-for-loop보다-느릴까-50dec4b9974b
        desc:
          type: string
          description: 해당 url 설명
          example: 실제 예시를 통한 비교 해둔 글
        category:
          type: string
          enum:
            - JAVA
            - SPRING
            - FOOD
            - WORK
          description: 글의 타입[JAVA, SPRING, FOOD, WORK]
          example: JAVA

    ErrorResponseDto:
      type: object
      properties:
        code:
          type: string
        message:
          type: string