openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'KDD Project'
  description: 'This project is created by kd 
  In this project, there are some techs with I learned'
servers:
  - url: http://localhost:8080
tags:
  - name: "독서"
    description: "독서 기록"
  - name: "링크"
    description: "링크 기록"

paths:

  /links:
    get:
      tags:
        - "링크"
      summary: 저장된 모든 링크 가져오기
      description: 모든 링크 리스트로 가져오기
      operationId: getAllLinks
      responses:
        200:
          description: SUCCESS
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/getLinkDto'
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
    post:
      tags:
        - "링크"
      summary: 단일 리스트 저장
      description: 단일 리스트 저장
      operationId: saveSingleLink
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/PostLinkDto'
      responses:
        200:
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getLinkDto'
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
    delete:
      tags:
        - "링크"
      summary: 저장된 모든 링크 삭제
      description: 모든 링크들 삭제
      operationId: deleteAllLinks
      responses:
        200:
          description: SUCCESS
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'


components:
  schemas:
    getLinkDto:
      type: object
      properties:
        id:
          type: integer
          description: 저장된 아이디(AUTO_INCREMENT)
          example: 1
        name:
          type: string
          description: 해당 url 이름
          example: Java Stream API는 왜 for-loop보다 느릴까?
        url:
          type: string
          description: 링크(raw url)
          example: https://jypthemiracle.medium.com/java-stream-api는-왜-for-loop보다-느릴까-50dec4b9974b
        memo:
          type: string
          description: 해당 url 설명
          example: 실제 예시를 통한 비교 해둔 글
        category:
          type: string
          enum:
            - JAVA
            - SPRING
            - FOOD
            - WORK
          description: 글의 타입[JAVA, SPRING, FOOD, WORK]
          example: JAVA
        created:
          type: date
          description: 엔티티 생성시간
        update:
          type: date

    PostLinkDto:
      type: object
      properties:
        name:
          type: string
          description: 해당 url 이름
          example: Java Stream API는 왜 for-loop보다 느릴까?
        url:
          type: string
          description: 링크(raw url)
          example: https://jypthemiracle.medium.com/java-stream-api는-왜-for-loop보다-느릴까-50dec4b9974b
        memo:
          type: string
          description: 해당 url 설명
          example: 실제 예시를 통한 비교 해둔 글
        category:
          type: string
          enum:
            - JAVA
            - SPRING
            - FOOD
            - WORK
          description: 글의 타입[JAVA, SPRING, FOOD, WORK]
          example: JAVA

    ErrorResponseDto:
      type: object
      properties:
        code:
          type: string
        message:
          type: string