openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'KDD Project'
  description: 'This project is created by kd 
  In this project, there are some techs with I learned'
servers:
  - url: http://localhost:8080
tags:
  - name: "Books"
    description: "독서 기록"
  - name: "Links"
    description: "링크 기록"

paths:

  /links:
    get:
      tags:
        - "Links"
      summary: 저장된 모든 링크 가져오기
      description: 모든 링크 리스트로 가져오기
      responses:
        200:
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostLinkDto'
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'
    post:
      tags:
        - "Links"
      summary: 리스트로 링크를 저장
      description: 리스트로 링크를 저장
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/PostLinkListDto'
      responses:
        200:
          description: SUCCESS
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'


  /swaggerTest:
    get:
      summary: simple swagger test api
      description: simple swagger test api
      responses:
        200:
          description: SUCCESS
          content:
            application/json:
              schema:
                type: string
                example: responseTest
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

components:
  schemas:
    PostLinkDto:
      type: object
      properties:
        name:
          type: string
          description: 해당 url 이름
          example: Java Stream API는 왜 for-loop보다 느릴까?
        url:
          type: string
          description: 링크(raw url)
          example: https://jypthemiracle.medium.com/java-stream-api는-왜-for-loop보다-느릴까-50dec4b9974b
        desc:
          type: string
          description: 해당 url 설명
          example: 실제 예시를 통한 비교 해둔 글
        category:
          type: string
          enum:
            - JAVA
            - SPRING
            - FOOD
            - WORK
          description: 글의 타입[JAVA, SPRING, FOOD, WORK]
          example: JAVA

    PostLinkListDto:
      type: array
      items:
        $ref: '#/components/schemas/PostLinkDto'

    ErrorResponseDto:
      type: object
      properties:
        code:
          type: string
        message:
          type: string