openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'KDD Project'
  description: 'This project is created by kd 
  In this project, there are some techs with I learned'
servers:
  - url: http://localhost:8080
tags:
  - name: "독서"
    description: "독서 기록"
  - name: "링크"
    description: "링크 기록"
  - name: "회원관리"
    description: "회원 관리"

paths:
  /link/{url}:
    get:
      tags:
        - "링크"
      summary: URL으로 link 조회
      description: URL으로 저장한 link를 조회
      operationId: findSingleLink
      parameters:
        - name: url
          in: path
          description: 저장해둔 링크를 URL으로 조회
          required: true
          schema:
            type: string
      responses:
        200:
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getLinkDto'
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'


  /link/find/{keyword}:
    get:
      tags:
        - "링크"
      summary: 입력받은 URL을 가진 링크 조회
      description: 입력값을 LIKE 키워드를 사용해 조회
      operationId: findLinksLikeUrl
      parameters:
        - name: keyword
          in: path
          description: 링크에 있는 단어를 기준으로 검색
          required: true
          schema:
            type: string
      responses:
        200:
          description: SUCCESS
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/getLinkDto'
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

  /link:
    post:
      tags:
        - "링크"
      summary: 단일 링크 저장
      description: 단일 링크 저장
      operationId: saveSingleLink
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/PostLinkDto'
      responses:
        200:
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getLinkDto'
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

  /links:
    get:
      tags:
        - "링크"
      summary: 저장된 모든 링크 가져오기
      description: 모든 링크 리스트로 가져오기
      operationId: getAllLinks
      responses:
        200:
          description: SUCCESS
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/getLinkDto'
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

    post:
      tags:
        - "링크"
      summary: 리스트로 링크 저장
      description: 리스트로 링크 저장
      operationId: saveLinkList
      requestBody:
        content:
          'application/json':
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PostLinkDto'
      responses:
        200:
          description: SUCCESS
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/getLinkDto'
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

    delete:
      tags:
        - "링크"
      summary: 저장된 모든 링크 삭제
      description: 모든 링크들 삭제
      operationId: deleteAllLinks
      responses:
        200:
          description: SUCCESS
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'

  /member:
    post:
      tags:
        - "회원"
      summary: 회원 등록
      description: 회원 등록
      operationId: postMember
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/PostMemberDto'
      responses:
        200:
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMemberDto'
        400:
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseDto'


components:
  schemas:
    getLinkDto:
      type: object
      properties:
        url:
          type: string
          description: 링크(raw url)
          example:
            https://jypthemiracle.medium.com/java-stream-api는-왜-for-loop보다-느릴까-50dec4b9974b
        name:
          type: string
          description: 해당 url 이름
          example: Java Stream API는 왜 for-loop보다 느릴까?
        memo:
          type: string
          description: 해당 url 설명
          example: 실제 예시를 통한 비교 해둔 글
        category:
          type: string
          enum:
            - JAVA
            - SPRING
            - FOOD
            - WORK
            - KOTLIN
          description: 글의 타입[JAVA, SPRING, FOOD, WORK, KOTLIN]
          example: JAVA
        created:
          type: string
          format: date-time
          description: 엔티티 생성시간
        update:
          type: string
          format: date-time
          description: 엔티티 수정시간

    PostLinkDto:
      type: object
      properties:
        name:
          type: string
          description: 해당 url 이름
          example: Java Stream API는 왜 for-loop보다 느릴까?
        url:
          type: string
          description: 링크(raw url)
          example: https://jypthemiracle.medium.com/java-stream-api는-왜-for-loop보다-느릴까-50dec4b9974b
        memo:
          type: string
          description: 해당 url 설명
          example: 실제 예시를 통한 비교 해둔 글
        category:
          type: string
          enum:
            - JAVA
            - SPRING
            - FOOD
            - WORK
            - KOTLIN
          description: 글의 타입[JAVA, SPRING, FOOD, WORK, KOTLIN]
          example: JAVA

    PostMemberDto:
      type: object
      properties:
        loginId:
          type: string
          description: 로그인시 받는 아이디
          example: playggg
        password:
          type: string
          description: 로그인시 저장되는 아이디
          example: rbeh!234
        role:
          type: string
          enum:
            - ADMIN
            - USER
          description: 사용자의 타입
          example: USER
        name:
          type: string
          description: 이름
          example: kdshim
        birthDateYYYYMMDD:
          type: string
          description: 생년월일
          example: 19970329
        married:
          type: boolean
          description: 결혼 여부
          example: false
        email:
          type: string
          description: 이메일
          example: kyudo97@naver.com
        oldAddr:
          type: string
          description: 지번주소
          example: 경기도 고양시 일산서구 주엽동 84
        addr:
          type: string
          description: 도로명주소
          example: 경기도 고양시 일산서구 강선로 30
        addrDetail:
          type: string
          description: 상세주소
          example: 1504동 1501호
        zipCode:
          type: integer
          description: 우편번호
          example: 10365

    GetMemberDto:
      type: object
      properties:
        loginId:
          type: string
          description: 로그인시 받는 아이디
          example: playggg
        password:
          type: string
          description: 로그인시 저장되는 아이디
          example: rbeh!234
        role:
          type: string
          enum:
            - ADMIN
            - USER
          description: 사용자의 타입
          example: USER
        name:
          type: string
          description: 이름
          example: kdshim
        birthDateYYYYMMDD:
          type: string
          description: 생년월일
          example: 19970329
        married:
          type: boolean
          description: 결혼 여부
          example: false
        email:
          type: string
          description: 이메일
          example: kyudo97@naver.com
        oldAddr:
          type: string
          description: 지번주소
          example: 경기도 고양시 일산서구 주엽동 84
        addr:
          type: string
          description: 도로명주소
          example: 경기도 고양시 일산서구 강선로 30
        addrDetail:
          type: string
          description: 상세주소
          example: 1504동 1501호
        zipCode:
          type: integer
          description: 우편번호
          example: 10365
        created:
          type: string
          format: date-time
          description: 엔티티 생성시간
        update:
          type: string
          format: date-time
          description: 엔티티 수정시간

    ErrorResponseDto:
      type: object
      properties:
        code:
          type: string
        message:
          type: string